### PR TITLE
translated localization to English and fixed some issues

### PR DESCRIPTION
**Pull request by Ceddix**
As the title says 😄 

**I'm not sure about some things tho:**
1. TrainCarts doesn't have a prefix on most of it's command, so we should probably remove it
2. There could still be some issues (I hope not haha)
3. I'm not sure if the `COMMAND_DESTINATION_INFO` and `COMMAND_DESTINATIONS_HEAD_CONTENT` are right or even look good, as I needed to remove some things from our private locale _(that we will add again in or localization.yml later)_

### CODE REVIEW

**Comment by Ceddix** [comment]
There were so many issues in your syntax btw many localizations wouldn't have worked hahaha

**Comment by J0schlZ** [comment]
> There were so many issues in your syntax btw many localizations wouldn't have worked hahaha

Which ones do you mean exactly?

We discussed the other points.

**Comment by Ceddix** [comment]
You can merge, I already fixed them :)

**Comment by J0schlZ** [comment]
Wasn't the question 😛

**Pull request merged**
